-- ANNEXURE B – Aided Engineering Colleges
INSERT INTO colleges (id, name, institution_type, college_code) VALUES
(26, 'B M S College of Engineering, Basavanagudi, Bangalore (Autonomous)', 'Aided Engineering Colleges', 'E003'),
(27, 'B V V Sangha''s Basaveshwara Engineering College, Bagalkote (Autonomous)', 'Aided Engineering Colleges', 'E031'),
(28, 'Dr. Ambedkar Institute of Technology, Bangalore (Autonomous)', 'Aided Engineering Colleges', 'E004'),
(29, 'Malnad College of Engineering, Hassan (Autonomous)', 'Aided Engineering Colleges', 'E024'),
(30, 'P D A College of Engineering, Gulbarga (Autonomous)', 'Aided Engineering Colleges', 'E041'),
(31, 'P E S College of Engineering, Mandya (Autonomous)', 'Aided Engineering Colleges', 'E023'),
(32, 'Sri Jayachamarajendra College of Engineering (Constituent College of JSS Science & Technology University), Mysore', 'Aided Engineering Colleges', 'E021'),
(33, 'The National Institute of Engineering, Mysore (Autonomous)', 'Aided Engineering Colleges', 'E022');

INSERT INTO courses (college_id, course_name) VALUES
(26, 'CIVIL ENGINEERING'), (26, 'ELECTRICAL AND ELECTRONICS ENGINEERING'), (26, 'ELECTRONICS AND COMMUNICATION ENGINEERING'), (26, 'INDUSTRIAL ENGINEERING AND MANAGEMENT'), (26, 'MECHANICAL ENGINEERING'),
(27, 'CIVIL ENGINEERING'), (27, 'COMPUTER SCIENCE AND ENGINEERING'), (27, 'ELECTRICAL AND ELECTRONICS ENGINEERING'), (27, 'ELECTRONICS AND COMMUNICATION ENGINEERING'), (27, 'INDUSTRIAL AND PRODUCTION ENGINEERING'), (27, 'MECHANICAL ENGINEERING'),
(28, 'CIVIL ENGINEERING'), (28, 'COMPUTER SCIENCE AND ENGINEERING'), (28, 'ELECTRICAL AND ELECTRONICS ENGINEERING'), (28, 'ELECTRONICS AND COMMUNICATION ENGINEERING'), (28, 'ELECTRONICS AND INSTRUMENTATION ENGINEERING'), (28, 'ELECTRONICS AND TELECOMMUNICATION ENGINEERING'), (28, 'INDUSTRIAL ENGINEERING AND MANAGEMENT'), (28, 'MECHANICAL ENGINEERING'),
(29, 'CIVIL ENGINEERING'), (29, 'ELECTRICAL AND ELECTRONICS ENGINEERING'), (29, 'ELECTRONICS AND COMMUNICATION ENGINEERING'), (29, 'MECHANICAL ENGINEERING'),
(30, 'CIVIL ENGINEERING'), (30, 'ELECTRICAL AND ELECTRONICS ENGINEERING'), (30, 'ELECTRONICS AND COMMUNICATION ENGINEERING'), (30, 'INDUSTRIAL AND PRODUCTION ENGINEERING'), (30, 'MECHANICAL ENGINEERING'),
(31, 'CIVIL ENGINEERING'), (31, 'ELECTRICAL AND ELECTRONICS ENGINEERING'), (31, 'ELECTRONICS AND COMMUNICATION ENGINEERING'), (31, 'MECHANICAL ENGINEERING'),
(32, 'CIVIL ENGINEERING'), (32, 'COMPUTER SCIENCE AND ENGINEERING'), (32, 'ELECTRICAL AND ELECTRONICS ENGINEERING'), (32, 'ELECTRONICS AND INSTRUMENTATION ENGINEERING'), (32, 'ELECTRONICS AND COMMUNICATION ENGINEERING'), (32, 'ENVIRONMENTAL ENGINEERING'), (32, 'INDUSTRIAL AND PRODUCTION ENGINEERING'), (32, 'MECHANICAL ENGINEERING'), (32, 'POLYMER SCIENCE AND TECHNOLOGY'),
(33, 'CIVIL ENGINEERING'), (33, 'ELECTRONICS AND COMMUNICATION ENGINEERING'), (33, 'MECHANICAL ENGINEERING');