-- All 31 Districts of Karnataka
INSERT INTO districts (id, name) VALUES
(1, 'Bagalkote'),
(2, 'Ballari'),
(3, 'Belagavi'),
(4, 'Bengaluru Rural'),
(5, 'Bengaluru Urban'),
(6, 'Bidar'),
(7, 'Chamarajanagar'),
(8, 'Chikkaballapur'),
(9, 'Chikkamagaluru'),
(10, 'Chitradurga'),
(11, 'Dakshina Kannada'),
(12, 'Davanagere'),
(13, 'Dharwad'),
(14, 'Gadag'),
(15, 'Hassan'),
(16, 'Haveri'),
(17, 'Kalaburagi'),
(18, 'Kodagu'),
(19, 'Kolar'),
(20, 'Koppal'),
(21, 'Mandya'),
(22, 'Mysuru'),
(23, 'Raichur'),
(24, 'Ramanagara'),
(25, 'Shivamogga'),
(26, 'Tumakuru'),
(27, 'Udupi'),
(28, 'Uttara Kannada'),
(29, 'Vijayanagara'),
(30, 'Vijayapura'),
(31, 'Yadgir');