-- ANNEXURE Z — Government Colleges with Higher Fees
INSERT INTO colleges (id, name, institution_type, college_code) VALUES
(233, 'Constituent College of VTU, Chintamani, Chikaballapura', 'Government Colleges with Higher Fees', 'E309'),
(234, 'University B.D.T College of Engineering, Davanagere', 'Government Colleges with Higher Fees', 'E066'),
(235, 'University of Mysuru', 'Government Colleges with Higher Fees', 'E283'),
(236, 'VTU Constituent Engineering College, Gokak', 'Government Colleges with Higher Fees', 'E315');

INSERT INTO courses (college_id, course_name) VALUES
(233, 'COMPUTER SCIENCE AND ENGINEERING'), (233, 'COMPUTER SCIENCE AND ENGINEERING (AIML)'), (233, 'ELECTRICAL AND ELECTRONICS ENGINEERING'), (233, 'ELECTRONICS AND COMMUNICATION ENGG'),
(234, 'CIVIL ENGINEERING'), (234, 'COMPUTER SCIENCE AND ENGINEERING'), (234, 'ELECTRICAL AND ELECTRONICS ENGINEERING'), (234, 'ELECTRONICS AND COMMUNICATION ENGG'), (234, 'ELECTRONICS AND INSTRUMENTATION ENGINEERING'), (234, 'MECHANICAL ENGINEERING'), (234, 'ROBOTICS AND ARTIFICIAL INTELLIGENCE'),
(235, 'ARTIFICIAL INTELLIGENCE AND DATA SCIENCE'), (235, 'ARTIFICIAL INTELLIGENCE AND MACHINE LEARNING'), (235, 'BIOMEDICAL AND ROBOTIC ENGINEERING'), (235, 'CIVIL ENVIRONMENTAL ENGINEERING'), (235, 'COMPUTER SCIENCE AND DESIGN'), (235, 'COMPUTER SCIENCE AND ENGINEERING'), (235, 'ELECTRONICS AND COMMUNICATION ENGG'),
(236, 'ARTIFICIAL INTELLIGENCE'), (236, 'B TECH IN CIVIL ENGINEERING'), (236, 'ELECTRICAL AND ELECTRONICS ENGINEERING');